version: '3.7'
services:

  squegtech-steam-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: squegtech/steam-api:latest
    container_name: squegtech-steam-api
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - squegtech-steam-api-network

# Docker Networks
networks:
  squegtech-steam-api-network:
